"""initial

Revision ID: 71a240e65e7f
Revises: 
Create Date: 2025-11-17 10:24:32.918073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71a240e65e7f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False, comment='Employee ID from Excel (business key)'),
    sa.Column('name', sa.String(length=300), nullable=True, comment='Employee full name from Excel'),
    sa.Column('department_code', sa.String(length=50), nullable=True, comment="Department code from Excel (e.g., 'HR', 'DEV', 'FIN', 'MKT')"),
    sa.Column('salary', sa.Float(), nullable=True, comment='Original salary amount from Excel'),
    sa.Column('hire_date', sa.Date(), nullable=True, comment='Employee hire date from Excel'),
    sa.Column('department_name', sa.String(length=200), nullable=True, comment='Transformed department name (mapped from department_code via config.csv)'),
    sa.Column('annual_salary_eur', sa.Float(), nullable=True, comment='Transformed annual salary in EUR (calculated from salary via config.csv)'),
    sa.Column('tenure_years', sa.Integer(), nullable=True, comment='Calculated years of service (from hire_date)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employee_department_code', 'employee', ['department_code'], unique=False)
    op.create_index('ix_employee_department_name', 'employee', ['department_name'], unique=False)
    op.create_index('ix_employee_employee_id', 'employee', ['employee_id'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(length=50), nullable=False, comment='Project ID from Excel (business key)'),
    sa.Column('project_name', sa.String(length=200), nullable=True, comment='Project name from Excel'),
    sa.Column('budget_usd', sa.Float(), nullable=True, comment='Budget amount in USD from Excel'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='Project start date from Excel'),
    sa.Column('status', sa.String(length=50), nullable=True, comment='Project status from Excel (Active, Complete, On Hold, Pending)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_project_id', 'project', ['project_id'], unique=True)
    op.create_index('ix_project_status', 'project', ['status'], unique=False)
    op.create_table('upload_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('processed_rows', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_job_status_created', 'upload_job', ['status', 'created_at'], unique=False)
    op.create_index('ix_upload_job_status', 'upload_job', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_upload_job_status', table_name='upload_job')
    op.drop_index('idx_upload_job_status_created', table_name='upload_job')
    op.drop_table('upload_job')
    op.drop_index('ix_project_status', table_name='project')
    op.drop_index('ix_project_project_id', table_name='project')
    op.drop_table('project')
    op.drop_index('ix_employee_employee_id', table_name='employee')
    op.drop_index('ix_employee_department_name', table_name='employee')
    op.drop_index('ix_employee_department_code', table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
